#!/usr/bin/env python3
"""
Google Sheets Updater - Updates the "Current Guidance" column (J) with buy prices.

Reads buy prices generated by EarningsBot and updates column J for matching
tickers found in column C of the existing Google Sheet.

IMPORTANT: This script never clears or overwrites existing sheet data.
It only updates column J for rows where the ticker matches.

Usage:
    python sheets_updater.py              # Update the Google Sheet
    python sheets_updater.py --dry-run    # Preview updates without writing
"""

import os
import sys
import json
import argparse
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

GOOGLE_SHEETS_ID = os.getenv("GOOGLE_SHEETS_ID", "19TQGyUC4FwKyW0vkzxF2HepnbyMHLLpA3LDaTcKtaY4")
SERVICE_ACCOUNT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "service_account.json")
BUY_PRICES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "buy_prices.json")

# Column positions (0-indexed)
TICKER_COL = 2    # Column C = Ticker
GUIDANCE_COL = 9  # Column J = Current Guidance


def load_buy_prices(filepath=BUY_PRICES_FILE):
    """Load buy prices from JSON file."""
    if not os.path.exists(filepath):
        print(f"No buy prices file found at {filepath}")
        return {}

    try:
        with open(filepath, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error reading buy prices file: {e}")
        return {}


def get_credentials_file():
    """Get the service account credentials file path."""
    if os.path.exists(SERVICE_ACCOUNT_FILE):
        return SERVICE_ACCOUNT_FILE

    # In GitHub Actions, credentials are written from a secret
    creds_json = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
    if creds_json:
        credentials_file = "/tmp/service_account.json"
        with open(credentials_file, "w") as f:
            f.write(creds_json)
        return credentials_file

    return None


def update_google_sheet(buy_prices, dry_run=False):
    """Update column J (Current Guidance) for matching tickers in column C."""
    if dry_run:
        print("\n[DRY RUN] Would update the following in column J:")
        for ticker, data in sorted(buy_prices.items()):
            buy_price = data.get("buy_price", "N/A")
            print(f"  {ticker} → Buy Below {buy_price}")
        return True

    # Import gspread here so --dry-run works without credentials
    import gspread

    credentials_file = get_credentials_file()
    if not credentials_file:
        print("Error: No service account credentials found")
        print("  Place service_account.json in the project directory")
        print("  Or set GOOGLE_SERVICE_ACCOUNT_JSON environment variable")
        return False

    try:
        gc = gspread.service_account(filename=credentials_file)
        sheet = gc.open_by_key(GOOGLE_SHEETS_ID).worksheet("Stocks")

        # Read all data to find ticker rows
        all_data = sheet.get_all_values()

        if not all_data:
            print("Sheet is empty - nothing to update")
            return False

        updated = 0

        for row_idx, row in enumerate(all_data):
            # Skip header row
            if row_idx == 0:
                continue

            # Get ticker from column C (index 2)
            if len(row) <= TICKER_COL:
                continue

            sheet_ticker = row[TICKER_COL].strip().upper()

            if sheet_ticker in buy_prices:
                buy_price = buy_prices[sheet_ticker].get("buy_price", "")
                guidance_value = f"Buy Below {buy_price}"

                # Update column J (row is 1-indexed in gspread)
                cell_ref = f"J{row_idx + 1}"
                sheet.update_acell(cell_ref, guidance_value)
                print(f"  Updated {sheet_ticker} → {guidance_value} (cell {cell_ref})")
                updated += 1

        if updated > 0:
            print(f"✅ Updated {updated} stock(s) in Google Sheet")
        else:
            print("No matching tickers found in sheet")

        return True

    except Exception as e:
        print(f"Error updating Google Sheet: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Update Google Sheet with buy prices")
    parser.add_argument("--dry-run", action="store_true", help="Preview updates without writing")
    args = parser.parse_args()

    # Load buy prices
    buy_prices = load_buy_prices()

    if not buy_prices:
        print("No buy prices to update")
        return

    print(f"Found {len(buy_prices)} stock(s) with buy prices")

    # Update sheet
    if update_google_sheet(buy_prices, dry_run=args.dry_run):
        if not args.dry_run:
            print(f"Sheet URL: https://docs.google.com/spreadsheets/d/{GOOGLE_SHEETS_ID}")
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
